### ISSUE TITLE
Could not find lib/meta/include

### ISSUE THREAD

**Issue by Carina-Cai** [zmij/afsm#25]
Hi maybe this is a silly question but I am trying to include this library in my project, and I couldn't find the file `lib/meta/include` under the root of this repository as stated in `README.md`. Or should I just include metapushkin as you suggested in another issue?
Thank you so much for your help!

**Comment by zmij** [comment]
You should have metapushkin library  in your include path

**Comment by Carina-Cai** [comment]
Thanks, I will give it a try.
